package analizadorlx.ui;

import analizadorlx.utilidades.Archivos;
import co.edu.uniquindio.compiladores.frontend.lexico.Analizador;
import co.edu.uniquindio.compiladores.frontend.lexico.Node;
import co.edu.uniquindio.compiladores.frontend.lexico.ParseException;
import co.edu.uniquindio.compiladores.frontend.lexico.SimpleNode;
import co.edu.uniquindio.compiladores.frontend.lexico.TokenMgrError;
import co.edu.uniquindio.compiladores.utils.Impresion;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 * Ventana del Proyecto Procesadores
 *
 * @author Gustavo Salgado, Jorbe Burbano, Cristian Toro Universidad del Quindio
 * Programa de Ingenieria de Sistemas y Computacion Asignatura: Procesadores
 * @version 1.0
 * @since 2018
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Instancia del controlador de los archivos
     */
    private Archivos archivoManager;

    String tituloVentana = ".:. HUQ - Analizador Sintáctico .:.";

    //Solo permitir analizar cuando se haya cargado un archivo
    boolean permitirAnalizar = false;

    //Ruta Archivo
    String rutaArchivo = "";

    private DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Estructura");

    /**
     * Metodo constructor de la ventana
     */
    public Ventana() {
        initComponents();

        setTitle(tituloVentana);
        setLocationRelativeTo(null);

        archivoManager = new Archivos();
        jTxtAreaConsola.setForeground(Color.blue);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        cEditor = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTxtAreaConsola = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        arbol = new javax.swing.JTree();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        bAnalizar = new javax.swing.JMenuItem();
        mCargar = new javax.swing.JMenuItem();
        mNuevo = new javax.swing.JMenuItem();
        mGuardar = new javax.swing.JMenuItem();
        mGuardarComo = new javax.swing.JMenuItem();
        mSalir = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        mAcercaDe = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        analizadorlx.utilidades.TextLineNumber tln = new analizadorlx.utilidades.TextLineNumber(cEditor);
        cEditor.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(cEditor);
        jScrollPane1.setRowHeaderView( tln );

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setAutoscrolls(true);

        jTxtAreaConsola.setColumns(20);
        jTxtAreaConsola.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        jTxtAreaConsola.setLineWrap(true);
        jTxtAreaConsola.setRows(5);
        jTxtAreaConsola.setTabSize(2);
        jScrollPane4.setViewportView(jTxtAreaConsola);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Consola");

        arbol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Arbol BNF");
        arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(arbol);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analizadorlx/ui/img/inicio.png"))); // NOI18N
        jMenu1.setText("Archivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        bAnalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analizadorlx/ui/img/analizar.png"))); // NOI18N
        bAnalizar.setText("Analizar");
        bAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnalizarActionPerformed(evt);
            }
        });
        jMenu1.add(bAnalizar);

        mCargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analizadorlx/ui/img/abrir.png"))); // NOI18N
        mCargar.setText("Cargar Archivo");
        mCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCargarActionPerformed(evt);
            }
        });
        jMenu1.add(mCargar);

        mNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analizadorlx/ui/img/nuevo.png"))); // NOI18N
        mNuevo.setText("Nuevo");
        mNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(mNuevo);

        mGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analizadorlx/ui/img/guardar.png"))); // NOI18N
        mGuardar.setText("Guardar");
        mGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(mGuardar);

        mGuardarComo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analizadorlx/ui/img/guardar.png"))); // NOI18N
        mGuardarComo.setText("Guardar como");
        mGuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGuardarComoActionPerformed(evt);
            }
        });
        jMenu1.add(mGuardarComo);

        mSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analizadorlx/ui/img/salir.png"))); // NOI18N
        mSalir.setText("Salir");
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mSalir);
        jMenu1.add(jSeparator1);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analizadorlx/ui/img/acerca.png"))); // NOI18N
        jMenu2.setText("Ayuda");

        mAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analizadorlx/ui/img/acerca_devs.png"))); // NOI18N
        mAcercaDe.setText("Acerca De");
        mAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAcercaDeActionPerformed(evt);
            }
        });
        jMenu2.add(mAcercaDe);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(814, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane3)))
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnalizarActionPerformed
        ejecutar();

    }//GEN-LAST:event_bAnalizarActionPerformed

    private void mCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCargarActionPerformed
        jTxtAreaConsola.setText("");
        cEditor.setText("");
        abrirJFileChooser();
    }//GEN-LAST:event_mCargarActionPerformed

    private void mGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGuardarActionPerformed
        if (!cEditor.getText().isEmpty()) {
            GuardarJFileChooser(rutaArchivo.isEmpty(), true);
        } else {
            JOptionPane.showMessageDialog(null, "Editor vacio, para guardar un archivo debe escribir codigo!");
        }
    }//GEN-LAST:event_mGuardarActionPerformed

    private void mGuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGuardarComoActionPerformed
        GuardarJFileChooser(true, true);
    }//GEN-LAST:event_mGuardarComoActionPerformed

    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mSalirActionPerformed

    private void mAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAcercaDeActionPerformed
        devsInfo();
    }//GEN-LAST:event_mAcercaDeActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void mNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNuevoActionPerformed
        nuevo();
    }//GEN-LAST:event_mNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbol;
    private javax.swing.JMenuItem bAnalizar;
    private javax.swing.JTextPane cEditor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTxtAreaConsola;
    private javax.swing.JMenuItem mAcercaDe;
    private javax.swing.JMenuItem mCargar;
    private javax.swing.JMenuItem mGuardar;
    private javax.swing.JMenuItem mGuardarComo;
    private javax.swing.JMenuItem mNuevo;
    private javax.swing.JMenuItem mSalir;
    // End of variables declaration//GEN-END:variables

    /**
     * Metodo Recursivo para llenar Arbol de Derivacion
     *
     * @param raiz Nodo Padre del Jtree
     * @param padre Nodo Inicial que se tomara para construir arbol
     */
    public void generarArbol(DefaultMutableTreeNode raiz, Node padre) {
        for (int i = 0; i < padre.jjtGetNumChildren(); i++) {
            Node nuevoPadre = padre.jjtGetChild(i);
            String finales = nuevoPadre.toString();
            if (nuevoPadre.jjtGetNumChildren() == 0) {
                finales += "(" + ((SimpleNode) nuevoPadre).jjtGetValue().toString() + ")";
            }
            DefaultMutableTreeNode nodo = new DefaultMutableTreeNode(finales);
            generarArbol(nodo, nuevoPadre);
            raiz.add(nodo);
        }
    }

    /**
     * Ejecutar Analizador Sintactico
     */
    private void ejecutar() {
        if (permitirAnalizar) {
            try {
                GuardarJFileChooser(false, false);

                //Borrar consola cuando se inicia el analisis
                jTxtAreaConsola.setText("");

                Analizador sintacticoA = new Analizador(new java.io.FileInputStream(rutaArchivo));
                sintacticoA.init();
                //sintacticoA.obtenerListadoTokens();

                sintacticoA.ReInit(new java.io.FileInputStream(rutaArchivo));
                SimpleNode nodo = sintacticoA.mathuq();
                System.out.println("anal.getErrores().size() " + sintacticoA.getErrores().size());

                if (sintacticoA.getErrores().isEmpty()) {
                    System.out.println("Nodo Principal  " + nodo);
                    System.out.println("Nodo Hijos " + nodo.jjtGetNumChildren());

                    raiz = new DefaultMutableTreeNode("Estructura");
                    generarArbol(raiz, nodo);
                    DefaultTreeModel modelo = new DefaultTreeModel(raiz);
                    arbol.setModel(modelo);
                    colorConsola(Color.BLUE);
                    String consola = "Analisis Sintáctico realizado con exito.";
                    jTxtAreaConsola.setText(consola);
                } else {
                    colorConsola(Color.RED);
                    String consola = Impresion.imprimirErrores(sintacticoA.getErrores());
                    jTxtAreaConsola.setText(consola);

                    DefaultMutableTreeNode raizError = new DefaultMutableTreeNode("No Arbol");
                    DefaultTreeModel modelo = new DefaultTreeModel(raizError);
                    arbol.setModel(modelo);
                }
            } catch (TokenMgrError te) {
                System.out.println("GUI - Se han encontrado errores lexicos.");
                System.out.println(te.getMessage());
                jTxtAreaConsola.setText("Errores Lexicos Encontrados, para poder analizar sintacticamente debe corregirlos primero.\n" + te.getMessage());
            } catch (ParseException e) {
                System.out.println("Analizador: Se han encontrado errores en Parse.");
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(this, "Upps!, Error Sintactico no controlado. Por favor reinicie la aplicacion e intente nuevamente con otro archivo.");
                jTxtAreaConsola.setText(e.getMessage());
            } catch (FileNotFoundException e) {
                System.out.println("Analizador: Error General");
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(this, "No se encuentra el Archivo, por favor revise las rutas:\n" + e.getMessage());
            }

        } else {
            String msj= "Para realizar un análisis Sintáctico\nse requiere cargar un archivo válido.\nPor favor abra un Archivo .huq o cree un nuevo archivo.";
            
            if ( rutaArchivo.isEmpty() && !cEditor.getText().isEmpty()){
                msj = "Para ejecutar analisis primero debe guardar el archivo.";
            }                     
            
            JOptionPane.showMessageDialog(null, msj);
        }

    }

    /**
     * Abre el archivo deseado
     */
    private void abrirJFileChooser() {
        JFileChooser fileChoser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter(".huq", "HUQ", "*.huq");
        fileChoser.setFileFilter(filtro);
        fileChoser.showOpenDialog(this);

        File archivo = fileChoser.getSelectedFile();

        if (null != archivo) {

            String contenido = archivoManager.leerArchivo(archivo);

            if (null != contenido) {
                permitirAnalizar = true;
                actualizarRutasArchivo(archivo);
                cEditor.setText(contenido);
            }
        } else {
            permitirAnalizar = false;
        }
    }

    /**
     * Guarda el archivo deseado
     *
     * @param guardarComo identifica si es un guardar o guardarComo
     */
    private boolean GuardarJFileChooser(boolean guardarComo, boolean callback) {
        boolean ban = false;
        boolean guarda = false;       
        
        if (guardarComo) {
            JFileChooser fileChoser = new JFileChooser();
            fileChoser.setSelectedFile(new File("miMarthUQ_" + System.currentTimeMillis() + ".huq"));
            fileChoser.setFileFilter(new FileNameExtensionFilter(".huq", "huq"));
            fileChoser.showSaveDialog(this);
            File nuevoArchivo = fileChoser.getSelectedFile();

            if (null != nuevoArchivo) {
                //guardarComo....
                guarda = archivoManager.guardar(cEditor.getText(), nuevoArchivo);
                actualizarRutasArchivo(nuevoArchivo);

                if (guarda) {
                    if (callback) {
                        JOptionPane.showMessageDialog(null, "Archivo guardado correctamente");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El archivo no pudo guardarse");
                }
            }
            ban = true;
        } else {
            guarda = archivoManager.guardar(cEditor.getText(), new File(rutaArchivo));
            if (guarda) {
                if (callback) {
                    JOptionPane.showMessageDialog(null, "Archivo guardado correctamente.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El archivo no pudo guardarse.");
            }
            ban = true;
        }
        return ban;
    }

    /**
     * Actualiza la ruta del archivo analizado
     *
     * @param archivo el archivo a actualizar
     */
    private void actualizarRutasArchivo(File archivo) {
        try {
            setTitle(tituloVentana + " | analizando : " + archivo.getCanonicalPath());
            rutaArchivo = archivo.getCanonicalPath();
            
            //Permite Analizar si actualiza las rutas
            permitirAnalizar = true;

        } catch (IOException ex) {
            Logger.getLogger(Ventana.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Informacion sobre los colaboradores del proyecto
     */
    private void devsInfo() {
        JOptionPane.showMessageDialog(null, "Fase II: Compilador\n"
                + "Universidad del Quindio 2018\n"
                + "Grupo:\n"
                + "Jorge Burbano - Cristian Toro - Gustavo Salgado");
    }

    /**
     * Cambiar Color Consola
     *
     * @param color Constante que representa el Color
     */
    private void colorConsola(Color color) {
        jTxtAreaConsola.setForeground(color);
    }

    /**
     * Reiniciar Ventana
     */
    private void nuevo() {
        DefaultMutableTreeNode raizError = new DefaultMutableTreeNode("No Arbol");
        DefaultTreeModel modelo = new DefaultTreeModel(raizError);
        arbol.setModel(modelo);
        
        cEditor.setText("");
        jTxtAreaConsola.setText("");
        
        rutaArchivo = "";
        
        permitirAnalizar = false;
    }

}
